name: CMake pipeline for mac build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          brew install libxcb
          brew install pillow
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --icon=global-network.icns frontend.py --name Connections --add-data=global-network.icns:. --add-data=global-network.ico:.

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: connections-mac-dist
          path: dist/
